apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: color
  namespace: codefresh-hosted
  labels:
    app: color
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo
    name: cfdemo
  project: default
  source:
    path: ./manifests/color/
    repoURL: https://github.com/Codefresh-training/codefresh-runtime-applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - createNamespace=true
    automated:
      prune: true
      selfHeal: true
