apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trioapp-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    codefresh.io/product: trio-app
spec:
  destination:
    name: cfdemo
    namespace: prod
  source:
    path: manifests/trio-app/aperture-prod
    repoURL: 'https://github.com/aperture-sci/DevOps'
    targetRevision: HEAD
    # plugin:
    #   name: kustomize-build-with-helm
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
